# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-09-17 15:42
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recetas', '0002_agente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Datos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(default=datetime.datetime(2018, 9, 17, 15, 42, 28, 437244), editable=False)),
                ('id_cuota', models.CharField(max_length=100)),
                ('monto', models.CharField(blank=True, max_length=100, null=True)),
                ('ticket', models.CharField(blank=True, max_length=1000, null=True)),
                ('total', models.CharField(blank=True, max_length=1000, null=True)),
                ('agente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='recetas.Agente')),
            ],
        ),
    ]
