# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-09-17 17:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recetas', '0004_auto_20180917_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datos',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 17, 17, 50, 45, 836517), editable=False),
        ),
    ]
