# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-09-17 20:21
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recetas', '0009_auto_20180917_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datos',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 17, 20, 21, 48, 172054), editable=False),
        ),
    ]
