# Generated by Django 2.0.2 on 2018-09-18 03:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recetas', '0016_auto_20180917_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datos',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 17, 22, 41, 17, 375457), editable=False),
        ),
    ]
