# Generated by Django 2.0.2 on 2018-09-18 03:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recetas', '0018_auto_20180917_2247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datos',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 17, 22, 51, 23, 683981), editable=False),
        ),
    ]
