# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-09-18 17:52
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recetas', '0019_auto_20180918_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datos',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 18, 17, 52, 51, 143051), editable=False),
        ),
    ]
