# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-09-18 22:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recetas', '0028_auto_20180918_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datos',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 18, 17, 7, 50, 541509), editable=False),
        ),
    ]
