# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-09-18 22:44
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recetas', '0029_auto_20180918_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datos',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 18, 17, 44, 20, 993299), editable=False),
        ),
        migrations.AlterField(
            model_name='datos',
            name='ticket',
            field=models.FileField(upload_to='ticket'),
        ),
    ]
