# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-09-18 22:48
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recetas', '0030_auto_20180918_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datos',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 18, 17, 48, 38, 264107), editable=False),
        ),
        migrations.AlterField(
            model_name='datos',
            name='ticket',
            field=models.FileField(blank=True, null=True, upload_to='static'),
        ),
    ]
