# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-09-19 14:54
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recetas', '0033_auto_20180918_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datos',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 19, 9, 54, 25, 953179), editable=False),
        ),
    ]
