# Generated by Django 2.0.2 on 2018-09-19 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recetas', '0033_auto_20180918_1802'),
        ('recetas', '0019_auto_20180917_2251'),
    ]

    operations = [
    ]
