# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-09-19 14:59
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recetas', '0034_auto_20180919_0954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datos',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 19, 9, 59, 3, 494538), editable=False),
        ),
    ]
