# Generated by Django 2.0.2 on 2018-09-19 03:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recetas', '0034_merge_20180918_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datos',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 18, 22, 22, 51, 773029), editable=False),
        ),
        migrations.AlterField(
            model_name='datos',
            name='ticket',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
