# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-09-19 17:26
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recetas', '0035_auto_20180919_0959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datos',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 19, 12, 26, 14, 94664), editable=False),
        ),
        migrations.AlterField(
            model_name='datos',
            name='ticket',
            field=models.FileField(blank=True, null=True, upload_to='static/'),
        ),
    ]
