# Generated by Django 2.0.2 on 2018-09-20 03:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recetas', '0035_auto_20180918_2222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datos',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 19, 22, 6, 19, 24015), editable=False),
        ),
    ]
