# Generated by Django 2.0.2 on 2018-09-20 03:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recetas', '0036_auto_20180919_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datos',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 19, 22, 14, 49, 185372), editable=False),
        ),
    ]
