# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-09-19 17:51
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recetas', '0037_auto_20180919_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datos',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 19, 12, 51, 58, 964309), editable=False),
        ),
    ]
