# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-09-26 16:34
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recetas', '0044_auto_20180926_1116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='usuario',
        ),
        migrations.AlterField(
            model_name='datos',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 26, 11, 34, 22, 352523), editable=False),
        ),
        migrations.DeleteModel(
            name='Perfil',
        ),
    ]
